### ISSUE TITLE
🐛 `NotExpression` not parsed as expected

### ISSUE THREAD

**Issue by candoumbe** [candoumbe/DataFilters#80]
## Usage Information ##

Package version : `0.9.0`

## Relevant Code / Invocations
```csharp
NotExpression expression = FilterTokenParser.Not.Parse(tokens):
```
     
## Expected Behavior
The resulting expression should be equivalent to 

```csharp
new NotExpression(new DateTimeExpression(new DateExpression(2047, 9, 9),
                                                              new TimeExpression(21, 20, 13, 72),
                                                              OffsetExpression.Zero)`
```

## Stacktrace / Exception
```
 Error: [xUnit.net 00:00:12.50]     Should parse NotExpression [FAIL]
    Failed Should parse NotExpression [364 ms]
    Error Message:
     FsCheck.Xunit.PropertyFailedException : 
  Falsifiable, after 12 tests (0 shrinks) (17009067639848937555,15653198766927556505)
  Last step was invoked with size of 13 and seed of (7451033126996600080,7231531698258523449):
  Original:
  {NotExpression [Expression = DateTimeExpression, EscapedParseableString = '2047-09-09T21:20:13.72Z', OriginalString = '2047-09-09T21:20:13.72Z'],EscapedParseableString = !2047-09-09T21:20:13.72Z}
  
  ---- Expected actual to be {NotExpression [Expression = DateTimeExpression, EscapedParseableString = '2047-09-09T21:20:13.72Z', OriginalString = '2047-09-09T21:20:13.72Z'],EscapedParseableString = !2047-09-09T21:20:13.72Z}, but found {NotExpression [Expression = DateTimeExpression, EscapedParseableString = '2047-09-09T21:20:13.72Z', OriginalString = '2047-09-09T21:20:13.72Z'],EscapedParseableString = !2047-09-09T21:20:13.72Z}.
    Stack Trace:
    
  ----- Inner Stack Trace -----
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
     at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
     at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
     at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
     at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
     at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
     at FluentAssertions.Primitives.ObjectAssertions`2.Be(TSubject expected, String because, Object[] becauseArgs)
     at DataFilters.UnitTests.Grammar.Parsing.FilterTokenParserTests.AssertThatShould_parse(FilterExpression actual, FilterExpression expected, String reason) in /Users/runner/work/DataFilters/DataFilters/test/DataFilters.UnitTests/Grammar/Parsing/FilterTokenParserTests.cs:line 1033
     at DataFilters.UnitTests.Grammar.Parsing.FilterTokenParserTests.Should_parse_NotExpression(NotExpression expected) in /Users/runner/work/DataFilters/DataFilters/test/DataFilters.UnitTests/Grammar/Parsing/FilterTokenParserTests.cs:line 384
  --- End of stack trace from previous location ---
     at FsCheck.Runner.invokeAndThrowInner@589-1.Invoke(Object[] o) in C:\Users\kurts\Projects\FsCheck\src\FsCheck\Runner.fs:line 592
     at <StartupCode$FSharp-Core>.$Reflect.Invoke@814-4.Invoke(T1 inp)
     at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
     at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
     at System.Lazy`1.CreateValue()
     at System.Lazy`1.get_Value()
     at FsCheck.Testable.Prop.safeForce[a](Lazy`1 body) in C:\Users\kurts\Projects\FsCheck\src\FsCheck\Testable.fs:line 145
```

**Comment by candoumbe** [comment]
Closed as stale

**Comment by candoumbe** [comment]
Same issue found in this [build](https://github.com/candoumbe/DataFilters/actions/runs/7738161293/job/21098446564)
